### ISSUE TITLE
Potential bug in `mint`

### ISSUE THREAD

**Issue by RadialFinance** [andrecronje/solidly#14]
I was going through the contracts and came across what seems like a bug. The _mint function here (https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1.sol#L75) sets the balance and total supply instead of adding to it.

I verified this by calling the mint function on the testnet as well (https://testnet.ftmscan.com/tx/0x000e710bd370fb98189ffcfe6c6880380b83f098a2d96dd32e001b52175f6bf5) which set the totalSupply to 1 (https://testnet.ftmscan.com/address/0xc30eb4dd0187aad1428b998b251aa7d124783905#readContract)

**Comment by StErMi** [comment]
yeah I think it should be `totalSupply += amount` like they decrease in the `burn`.

same thing should be done for the `balanceOf[_to] = _amount` that should be `balanceOf[_to] += _amount`

**Comment by StErMi** [comment]
I also think that's old code because if you see the same function in https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1-core.sol#L679 it's fixed.

the codebase is a little bit confusing tbh. it's not easy to audit without understanding what's old and deprecated and what will be used.

**Comment by RadialFinance** [comment]
> I also think that's old code because if you see the same function in https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1-core.sol#L679 it's fixed.

That is a different contract related to Liquidity Pools. Token contract code is available in  https://testnet.ftmscan.com/address/0xc30eb4dd0187aad1428b998b251aa7d124783905#code and this issue is present there as well.

I think related code is https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1.sol but in deployed code, guard for mint is commented out.

**Comment by RadialFinance** [comment]
@andrecronje the same issue is there in Token.sol as well btw (https://github.com/andrecronje/solidly/blob/master/contracts/Token.sol#L83)

might not matter if it isn't used anywhere
