### ISSUE TITLE
Consider addressing 0xKydo analysis

### ISSUE THREAD

**Issue by BarnabyBob** [andrecronje/solidly#38]
- https://twitter.com/0xkydo/status/1487598011765035009
- https://kydo.substack.com/p/how-to-build-the-promised-ve33

**Comment by andrecronje** [comment]
Nothing to address, its based on incorrect assumptions, can review the code [here](https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1-minter.sol) or check the simulation [here](https://github.com/andrecronje/solidly/blob/master/scripts/minter.js)
