### ISSUE TITLE
can't create liquidity

### ISSUE THREAD

**Issue by zeoio** [andrecronje/solidly#44]
such as:

![Screenshot from 2022-02-05 21-51-58](https://user-images.githubusercontent.com/20078398/152644916-36a99573-f2ca-478a-a3d4-1ae97b0b13e8.png)
![Screenshot from 2022-02-05 21-52-05](https://user-images.githubusercontent.com/20078398/152644918-03a6a9ec-76aa-4a0a-a2cb-c58adbdc509b.png)

**Comment by andrecronje** [comment]
This repo is for the smart contracts only.
