### ISSUE TITLE
Massive slippage on swap even with slippage percentage set on trade

### ISSUE THREAD

**Issue by simplyprash** [andrecronje/solidly#48]
![image](https://user-images.githubusercontent.com/89380516/153403563-43afe766-9a40-4ddc-beaf-86fa66ee0515.png)

I swapped 350 FMT for BOO and received 0.3 BOO even when slippage was set to 2%

**Comment by simplyprash** [comment]
If the pool size was $25, shouldn't I have gotten an "Insufficient liquidity for the trade" error? Also, the transaction should have failed if the swap price moved beyond 2% slippage, rather '0' was passed to amountOutMin in the transaction. Isn't this a bug?

**Comment by ftm1337** [comment]
This is a User Interface / FrontEnd bug.

On the Contract level:
- Liquidity is always *sufficient* in an Automated Market Maker.
- Swap price did not *move* between your order submission & execution, hence the transaction did not revert.
