### ISSUE TITLE
Questions about minting rules

### ISSUE THREAD

**Issue by yiteng-guo** [andrecronje/solidly#49]
Hi, I have two questions about minting rules. I probably should ask this in discord/telegram but I couldn't find it. Please redirect me to the correct place if needed.

1. When BaseV1Minter is initialized (https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1-minter.sol#L71), it mints more than what it needs to distribute to top protocols. The extra tokens are held by the minter contract and let's call it "minter's reserve". When rewards are distributed from the minter's reserve, the total supply won't increase but we still calculate ve growth and distribute them to veNFT. With that said, if we initialize the minter with 20% allocated to top protocols, top protocols will control more than 20% of the total supply after rewards are paid out. Is this expected?
2. After minter's reserve is depleted, the minter will mint fresh tokens as weekly reward and ve growth. Note that we calculate the growth as `locked_supply * weekly / total_supply` (https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1-minter.sol#L105). I think this calculation gives less tokens to ve lockers than what they deserve. My reasoning is that if we want to ensure veNFT never gets diluted, we want to make sure `locked_reward / locked_supply = circulating_reward / circulating_supply`. Here, `locked_reward` is `growth` and `circulating_reward` is `weekly`. Then we can write this equation into `growth = locked_supply * weekly / circulating_supply`. The formula used in the smart contract has `total_supply` in the denominator instead, which will make this number smaller.

To demonstrate these two questions, I wrote a simple python simulation class with parameters that the mainnet deployment uses. The `user_locked_ratio` is the ratio of weekly rewards users will lock. I assume it is 0.5 in my experiment.
```
class Minter:
    def __init__(self, user_locked_ratio = 0.5):
        self.total_supply = 100
        self.protocol_controlled_supply = 20
        self.locked_supply = 20
        self.reserve = 80
        self.week = 0
        self.weekly = 20
        self.user_locked_ratio = user_locked_ratio
    
    @property
    def circulating_supply(self):
        return self.total_supply - self.locked_supply
    
    @property
    def calculate_emission(self):
        return self.weekly * 0.98 * self.circulating_supply / self.total_supply
    
    @property
    def circulating_emission(self):
        return self.circulating_supply * 0.002
    
    @property
    def weekly_emission(self):
        return max(self.calculate_emission, self.circulating_emission)
    
    def calculate_growth(self, minted):
        return self.locked_supply * minted / self.total_supply
    
    def info(self):
        print(f"circulating_supply: {self.circulating_supply} ({self.circulating_supply / self.total_supply})")
        print(f"locked_supply: {self.locked_supply} ({self.locked_supply / self.total_supply})")
        print(f"reserve: {self.reserve}")
        circulating_supply_excluding_reserve = self.circulating_supply - self.reserve
        print(f"circulating supply excluding minter reserve: {circulating_supply_excluding_reserve} ({circulating_supply_excluding_reserve / self.total_supply})")
        print(f"protocol controlled supply: {self.protocol_controlled_supply} ({self.protocol_controlled_supply / self.total_supply})")
        print(f"total supply: {self.total_supply}")
    
    def next_week(self):
        self.week += 1
        print(f"week {self.week}")
        weekly = self.weekly_emission
        print(f"is tail emission: {weekly == self.circulating_emission}")
        self.weekly = weekly
        growth = self.calculate_growth(weekly)
        distribute = weekly + growth
        print(f"weekly emission: {weekly} ({weekly / distribute})")
        print(f"ve growth: {growth} ({growth / distribute})")
        if distribute > self.reserve:
            print(f"mint {distribute - self.reserve}")
            self.reserve = 0
            self.total_supply += distribute - self.reserve
        else:
            print(f"distribute {distribute} from reserve.")
            self.reserve -= distribute
        self.protocol_controlled_supply += growth
        self.locked_supply += growth + self.user_locked_ratio * weekly
        self.info()

m = Minter(0.5)
for i in range(300):
    m.next_week()
```
After week 1, we can see the protocol controlled supply has already exceeded 20% as what I described in question 1.
```
week 1
is tail emission: False
weekly emission: 15.68 (0.8333333333333334)
ve growth: 3.136 (0.16666666666666669)
distribute 18.816 from reserve.
circulating_supply: 69.024 (0.69024)
locked_supply: 30.976 (0.30976)
reserve: 61.184
circulating supply excluding minter reserve: 7.840000000000003 (0.07840000000000004)
protocol controlled supply: 23.136 (0.23135999999999998)
total supply: 100
```
On week 247, minter's reserve is depleted. The ve growth is only 41.6% of the total reward token minted while the locked supply is 71.4%.
```
week 247
is tail emission: True
weekly emission: 0.057229352592414504 (0.5832900898191317)
ve growth: 0.04088538241047292 (0.41670991018086834)
mint 0.09811473500288742
circulating_supply: 28.64329097250345 (0.28559311953111355)
locked_supply: 71.65076029711386 (0.7144068804688865)
reserve: 0
circulating supply excluding minter reserve: 28.64329097250345 (0.28559311953111355)
protocol controlled supply: 43.06234519743852 (0.4293609107650401)
total supply: 100.29405126961731
```

Please correct me if my understanding on minting rules above is wrong. Thank you!

**Comment by andrecronje** [comment]
Your understanding is correct, inflation takes into account minted (aka that which go into circulating) and not locked (aka that which is distributed by ve-dist to veNFT holders). Their ownership should increase based on minted circulating supply, not total weekly minted (otherwise they would be double counting their own locked values)
