### ISSUE TITLE
Question about reward calculation checkpoint range

### ISSUE THREAD

**Issue by yiteng-guo** [andrecronje/solidly#50]
Hey, I have a quick question about reward calculation in `BaseV1-gauges.sol`. 

I noticed that in these two places [_updateRewardPerToken](https://github.com/andrecronje/solidly/blob/eac1ef02ca8736138b25062c02646ea43d5bb6e4/contracts/BaseV1-gauges.sol#L416) and [earned](https://github.com/andrecronje/solidly/blob/eac1ef02ca8736138b25062c02646ea43d5bb6e4/contracts/BaseV1-gauges.sol#L452), the for loop goes from `startIndex` to `endIndex-1` while in [_batchRewardPerToken](https://github.com/andrecronje/solidly/blob/master/contracts/BaseV1-gauges.sol#L381), the for loop goes from `startIndex` to `endIndex`. Based on my understanding, going from `startIndex` to `endIndex-1` will miss one checkpoint period between `endIndex-1` and `endIndex`.

Is there something I'm missing?

**Comment by andrecronje** [comment]
endIndex is only processed when a claim happens that needs to claim up to current timestamp, _batchReward is meant for batching if there is gas exhaustion, so batching should not process up to current timestamp.

**Comment by yiteng-guo** [comment]
Hi, I just want to emphasize the consequence of this bug: Users could lose a large chunk of their pending gauge rewards if they do a deposit/withdrawal right before collecting the reward.
